all:
	gcc -g -D BUFFER_SIZE=1 get_next_line.c get_next_line_utils.c main.c
cp:
	rm GNL_lover/copy_in_here_GNL_files/get_next_line*
	cp get_next_line_utils.c get_next_line.c get_next_line.h GNL_lover/copy_in_here_GNL_files/
